spring:
  profile:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 10MB


springdoc:
  default-produce-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
