spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/book_social_network
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: localhost
        port: 1025
        username: mostafa
        password: mostafa
        properties:
            mail:
              smtp:
                trust: "*"
              auth: true
              starttls:
                enable: true
              connectiontimeout: 5000
              timeout: 3000
              writetomeout: 5000


application:
  security:
    jwt:
      secret-key: O5ZYarwNcV
      expiration: 86400000
